import type { PlatformSnapshot } from "./types";

export const demoSnapshot: PlatformSnapshot = {
  bootstrap: {
    viewer: {
      id: "usr_admin",
      display_name: "Ops Control",
      role: "admin",
      organization_id: "org_acme",
      workspace_id: "ws_core",
    },
    navigation: [
      {
        id: "inbox",
        label: "Inbox",
        path: "/inbox",
        description: "Triage, review, and intervention queues",
      },
      {
        id: "objectives",
        label: "Objectives",
        path: "/objectives",
        description: "Objective and blueprint overview",
      },
      {
        id: "queue",
        label: "Queue",
        path: "/queue",
        description: "Work item leasing and backlog pressure",
      },
      {
        id: "runs",
        label: "Runs",
        path: "/runs",
        description: "Execution timelines, logs, and artifacts",
      },
      {
        id: "reviews",
        label: "Reviews",
        path: "/reviews",
        description: "Automated and human review outcomes",
      },
      {
        id: "findings",
        label: "Findings",
        path: "/findings",
        description: "Incidents, risks, and defects",
      },
      {
        id: "insights",
        label: "Insights",
        path: "/insights",
        description: "Codified learnings and patterns",
      },
      {
        id: "workers",
        label: "Workers",
        path: "/workers",
        description: "Connected local worker daemons",
      },
    ],
    status_catalog: [
      {
        entity: "objective",
        statuses: [
          "submitted",
          "triaged",
          "planned",
          "executing",
          "reviewing",
          "done",
          "failed",
          "canceled",
        ],
      },
      {
        entity: "blueprint",
        statuses: ["draft", "approved", "rejected", "superseded"],
      },
      {
        entity: "work_item",
        statuses: [
          "queued",
          "leased",
          "running",
          "produced",
          "review_pending",
          "accepted",
          "rejected",
          "abandoned",
        ],
      },
      {
        entity: "execution",
        statuses: [
          "created",
          "assigned",
          "active",
          "succeeded",
          "failed",
          "timed_out",
          "canceled",
        ],
      },
      {
        entity: "review",
        statuses: ["pending", "accepted", "rejected", "split_required"],
      },
      {
        entity: "finding",
        statuses: ["open", "acknowledged", "resolved", "dismissed"],
      },
      {
        entity: "insight",
        statuses: ["draft", "published", "retired"],
      },
    ],
    boards: {
      objective_board: {
        submitted: 2,
        planned: 3,
        executing: 5,
        reviewing: 2,
      },
      queue_board: {
        queued: 11,
        leased: 4,
        running: 6,
        review_pending: 3,
      },
      run_timeline: {
        active: 6,
        timed_out: 1,
        failed: 2,
        completed_today: 14,
      },
      review_inbox: {
        pending: 4,
        split_required: 1,
        rejected: 2,
      },
      worker_health: {
        online: 3,
        degraded: 1,
        offline: 1,
      },
    },
  },
  orgs: [{ id: "org_acme", name: "Acme Delivery", slug: "acme-delivery" }],
  workspaces: [
    {
      id: "ws_core",
      organization_id: "org_acme",
      name: "Core Platform",
      slug: "core-platform",
      environment: "production-mirror",
    },
  ],
  repositories: [
    {
      id: "repo_dpring",
      workspace_id: "ws_core",
      name: "dp-ring",
      default_branch: "main",
      clone_url: "ssh://git.example.com/acme/dp-ring.git",
      bound_worker_ids: ["wrk_shanghai", "wrk_berlin"],
    },
  ],
  objectives: [
    {
      id: "obj_inbox_rebuild",
      workspace_id: "ws_core",
      title: "Rebuild operator inbox around event-driven review lanes",
      summary: "Replace artifact-centric UI with board-driven operator lanes.",
      status: "executing",
      priority: "critical",
      repository_id: "repo_dpring",
      blueprint_id: "bp_inbox_rebuild",
      active_work_item_ids: ["wi_nav_registry", "wi_sse_stream"],
      updated_at: "2026-04-15T12:00:00.000Z",
    },
    {
      id: "obj_rbac_cutover",
      workspace_id: "ws_core",
      title: "Ship org-level RBAC for control-plane mutation APIs",
      summary: "Enforce admin/operator/reviewer/worker role gates in control-api.",
      status: "reviewing",
      priority: "high",
      repository_id: "repo_dpring",
      blueprint_id: "bp_rbac_cutover",
      active_work_item_ids: ["wi_claim_mapper"],
      updated_at: "2026-04-15T12:00:00.000Z",
    },
  ],
  blueprints: [
    {
      id: "bp_inbox_rebuild",
      objective_id: "obj_inbox_rebuild",
      status: "approved",
      summary:
        "Create intake, queue, run, review, incident, and insight surfaces from read models.",
      steps: [
        {
          id: "bpstep_1",
          title: "Board read models",
          summary: "Publish aggregate counters for all work lanes.",
        },
        {
          id: "bpstep_2",
          title: "Navigation metadata",
          summary: "Serve operator surfaces from control-api bootstrap.",
        },
        {
          id: "bpstep_3",
          title: "SSE activity rail",
          summary: "Stream domain activity into the console.",
        },
      ],
    },
    {
      id: "bp_rbac_cutover",
      objective_id: "obj_rbac_cutover",
      status: "draft",
      summary:
        "Introduce organization/workspace-aware claim validation and role enforcement.",
      steps: [
        {
          id: "bpstep_4",
          title: "Keycloak discovery",
          summary: "Read issuer, audience, and JWKS from config.",
        },
        {
          id: "bpstep_5",
          title: "Route policies",
          summary: "Map role permissions to command endpoints.",
        },
      ],
    },
  ],
  work_items: [
    {
      id: "wi_nav_registry",
      objective_id: "obj_inbox_rebuild",
      blueprint_id: "bp_inbox_rebuild",
      title: "Serve operator navigation from bootstrap payload",
      status: "running",
      owner_lane: "ui-metadata",
      acceptance_contract: [
        "Bootstrap payload includes eight operator surfaces.",
        "Console renders navigation from API metadata only.",
      ],
      scope: {
        repository_id: "repo_dpring",
        target_path: "apps/operator-web/src",
        file_allowlist: ["src/routes", "src/layouts"],
        build_command: "npm run build",
        cleanup_paths: ["apps/operator-web/dist"],
      },
    },
    {
      id: "wi_sse_stream",
      objective_id: "obj_inbox_rebuild",
      blueprint_id: "bp_inbox_rebuild",
      title: "Expose activity stream from control-api",
      status: "review_pending",
      owner_lane: "control-api",
      acceptance_contract: [
        "SSE stream emits domain events with resource links.",
        "Frontend timeline updates without polling.",
      ],
      scope: {
        repository_id: "repo_dpring",
        target_path: "services/control-api/src",
        file_allowlist: ["src/main.rs"],
        build_command: null,
        cleanup_paths: [],
      },
    },
    {
      id: "wi_claim_mapper",
      objective_id: "obj_rbac_cutover",
      blueprint_id: "bp_rbac_cutover",
      title: "Map OIDC claims into workspace-scoped viewer roles",
      status: "produced",
      owner_lane: "auth",
      acceptance_contract: [
        "Viewer claims include org and workspace identifiers.",
        "Mutation routes reject unsupported roles.",
      ],
      scope: {
        repository_id: "repo_dpring",
        target_path: "services/control-api/src/auth",
        file_allowlist: ["src/main.rs"],
        build_command: null,
        cleanup_paths: [],
      },
    },
  ],
  executions: [
    {
      id: "exe_shanghai_001",
      work_item_id: "wi_nav_registry",
      worker_id: "wrk_shanghai",
      status: "active",
      launched_at: "2026-04-15T12:00:00.000Z",
      completed_at: null,
      progress_percent: 62,
      artifact_manifest: [
        {
          kind: "console-log",
          uri: "s3://dp-ring/artifacts/exe_shanghai_001/log.txt",
        },
      ],
    },
    {
      id: "exe_berlin_014",
      work_item_id: "wi_sse_stream",
      worker_id: "wrk_berlin",
      status: "succeeded",
      launched_at: "2026-04-15T12:00:00.000Z",
      completed_at: "2026-04-15T12:10:00.000Z",
      progress_percent: 100,
      artifact_manifest: [
        {
          kind: "patch",
          uri: "s3://dp-ring/artifacts/exe_berlin_014/patch.diff",
        },
      ],
    },
  ],
  reviews: [
    {
      id: "rev_001",
      work_item_id: "wi_sse_stream",
      execution_id: "exe_berlin_014",
      status: "pending",
      verdict: "awaiting-human",
      reviewer: "review-bot",
      notes: "SSE semantics look correct. Confirm client retry policy.",
    },
    {
      id: "rev_002",
      work_item_id: "wi_claim_mapper",
      execution_id: "exe_berlin_014",
      status: "split_required",
      verdict: "split",
      reviewer: "ops-review",
      notes: "Separate discovery, verification, and policy mapping concerns.",
    },
  ],
  findings: [
    {
      id: "fdg_001",
      workspace_id: "ws_core",
      title: "Worker timeout threshold too aggressive for artifact uploads",
      status: "open",
      severity: "major",
      source_execution_id: "exe_shanghai_001",
    },
  ],
  insights: [
    {
      id: "ins_001",
      workspace_id: "ws_core",
      title: "Expose queue pressure as first-class board metric",
      status: "published",
      category: "control-plane",
      excerpt:
        "Operators react faster when backlog, lease, and review counts share the same view.",
    },
  ],
  workers: [
    {
      id: "wrk_shanghai",
      workspace_id: "ws_core",
      display_name: "Shanghai daemon",
      status: "online",
      capacity: 4,
      active_executions: 2,
      repository_ids: ["repo_dpring"],
      capabilities: ["git", "build", "artifact-upload"],
    },
    {
      id: "wrk_berlin",
      workspace_id: "ws_core",
      display_name: "Berlin daemon",
      status: "degraded",
      capacity: 3,
      active_executions: 1,
      repository_ids: ["repo_dpring"],
      capabilities: ["git", "build", "review-packet"],
    },
  ],
  activity: [
    {
      id: "evt_001",
      timestamp: "2026-04-15T12:00:00.000Z",
      kind: "objective.submitted.v1",
      title: "Objective submitted",
      summary: "Rebuild operator inbox entered triage.",
      resource_type: "objective",
      resource_id: "obj_inbox_rebuild",
    },
    {
      id: "evt_002",
      timestamp: "2026-04-15T12:01:00.000Z",
      kind: "workitem.queued.v1",
      title: "Work item queued",
      summary: "Serve operator navigation from bootstrap payload.",
      resource_type: "work_item",
      resource_id: "wi_nav_registry",
    },
    {
      id: "evt_003",
      timestamp: "2026-04-15T12:02:00.000Z",
      kind: "execution.assigned.v1",
      title: "Execution assigned",
      summary: "Shanghai daemon accepted lease for inbox work item.",
      resource_type: "execution",
      resource_id: "exe_shanghai_001",
    },
    {
      id: "evt_004",
      timestamp: "2026-04-15T12:03:00.000Z",
      kind: "review.completed.v1",
      title: "Review split required",
      summary: "RBAC claim mapping must be decomposed.",
      resource_type: "review",
      resource_id: "rev_002",
    },
    {
      id: "evt_005",
      timestamp: "2026-04-15T12:04:00.000Z",
      kind: "finding.opened.v1",
      title: "Finding opened",
      summary: "Artifact upload timeout threshold raised for investigation.",
      resource_type: "finding",
      resource_id: "fdg_001",
    },
    {
      id: "evt_006",
      timestamp: "2026-04-15T12:05:00.000Z",
      kind: "insight.published.v1",
      title: "Insight published",
      summary: "Queue pressure now drives operator priority views.",
      resource_type: "insight",
      resource_id: "ins_001",
    },
  ],
};
