import { execFile } from 'node:child_process';
import { createHmac } from 'node:crypto';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, extname, isAbsolute, join, resolve } from 'node:path';
import { promisify } from 'node:util';

const execFileAsync = promisify(execFile);

const DEFAULT_AUTOMATION_CONFIG = {
  enabled: false,
  loopback_agents: true,
  loopback_worker: true,
  auto_judge: true,
  auto_replan: true,
  max_replan_depth: 1,
  worker_id: 'worker-agent',
  judge_agent_id: 'task-judge',
  replanner_agent_id: 'task-replanner',
  commit_message_prefix: 'ring auto',
  default_callback_protocol: 'ring.workflow-run-report.v1',
};

const RING_REPORT_PROTOCOL = 'ring.workflow-run-report.v1';
const A2A_REPORT_PROTOCOL = 'a2a.task-status.v1';

function nowIso() {
  return new Date().toISOString();
}

function mergeAutomationConfig(config = {}) {
  return {
    ...DEFAULT_AUTOMATION_CONFIG,
    ...(config.automation ?? {}),
  };
}

function trimString(value) {
  return typeof value === 'string' && value.trim() ? value.trim() : null;
}

function normalizePathList(values) {
  if (!Array.isArray(values)) {
    return [];
  }
  return [...new Set(
    values
      .map((value) => (typeof value === 'string' ? value.trim().replace(/\\/g, '/') : ''))
      .filter(Boolean),
  )];
}

async function runGit(repoCwd, args) {
  const { stdout } = await execFileAsync('git', ['-C', repoCwd, ...args], {
    encoding: 'utf-8',
  });
  return stdout.trim();
}

async function ensureGitIdentity(repoCwd) {
  const email = await runGit(repoCwd, ['config', '--get', 'user.email']).catch(() => '');
  if (!email) {
    await runGit(repoCwd, ['config', 'user.email', 'loopback@dp-ring.local']);
  }
  const name = await runGit(repoCwd, ['config', '--get', 'user.name']).catch(() => '');
  if (!name) {
    await runGit(repoCwd, ['config', 'user.name', 'dp-ring Loopback']);
  }
}

function resolveTaskRepoRoot(repoRoot, task) {
  const scopedRoot = trimString(task?.data?.scope?.repo_root);
  if (!scopedRoot) {
    return repoRoot;
  }
  return isAbsolute(scopedRoot) ? scopedRoot : resolve(repoRoot, scopedRoot);
}

function splitAcceptanceCriteria(items = []) {
  if (!Array.isArray(items) || items.length === 0) {
    return ['Deliver the scoped output.', 'Leave a traceable summary for downstream execution.'];
  }
  return items.map((item) => trimString(item?.description) ?? trimString(item) ?? null).filter(Boolean);
}

function requirementDocument(requirement, job) {
  const criteria = splitAcceptanceCriteria(requirement.data.acceptance_criteria);
  const priority = trimString(requirement.data.priority) ?? 'normal';
  return `# ${requirement.data.name}

> Requirement ${requirement.id}
> Auto-generated by the loopback writer

## Goal

${requirement.data.description}

This document turns the incoming requirement into a durable execution brief that
the rest of the dispatcher can continue from without manual intervention. The
goal is to preserve the intent, surface the working constraints, and keep the
success contract explicit before milestone planning starts.

## Scope And Constraints

- Priority: ${priority}
- Routing mode: ${job.routing?.mode ?? 'standard'}
- Workflow strategy: ${job.routing?.workflow_strategy ?? 'reuse_first'}
- Deliverable must be clear enough for milestone planning and readiness routing

## Delivery Notes

The implementation should keep the requirement stable, preserve the original
goal, and reduce ambiguity before the orchestration pipeline moves into
milestones. The writer should explicitly capture the expected outcome, the
operating assumptions, and the success conditions so that later agents can work
from the document instead of inferring hidden context.

The document also needs to reflect that the system is expected to continue in an
automated way. That means the scope has to be specific enough for milestone
planning, prerequisite analysis, workflow selection, and session launch to make
deterministic decisions with minimal human intervention.

## Acceptance Criteria

${criteria.map((criterion) => `- ${criterion}`).join('\n')}

## Automation Notes

- The next stage should be able to split this requirement into milestones.
- The milestone planner should not need any hidden context outside this file.
- The dispatcher should be able to trace the goal back to requirement ${requirement.id}.
`;
}

function milestoneName(index, criteria) {
  if (criteria.length === 0) {
    return index === 0 ? 'Foundation' : 'Delivery';
  }
  if (index === 0) {
    return 'Foundation';
  }
  if (index === criteria.length) {
    return 'Validation';
  }
  return `Delivery ${index}`;
}

function milestonePlanDocument(requirement) {
  const criteria = splitAcceptanceCriteria(requirement.data.acceptance_criteria);
  const milestoneCount = Math.max(2, Math.min(criteria.length + 1, 3));
  const sections = [];

  for (let index = 0; index < milestoneCount; index += 1) {
    const title = milestoneName(index, criteria);
    const acceptanceSlice =
      index < criteria.length
        ? [criteria[index]]
        : criteria.slice(-1).length > 0
          ? criteria.slice(-1)
          : ['The implementation is stable enough to continue.'];
    const prerequisiteLine =
      index === 0
        ? '[reference] Requirement document is approved'
        : '[reference] Previous milestone outputs are available';
    sections.push(`## Milestone ${index + 1}: ${title}

This milestone translates the approved requirement into an executable chunk of
work with a clear outcome, bounded expectations, and enough context for the
downstream dispatcher to continue automatically.

### Acceptance Checks

${acceptanceSlice.map((criterion) => `- ${criterion}`).join('\n')}

### Prerequisites

- ${prerequisiteLine}`);
  }

  return `# ${requirement.data.name} Milestone Plan

> Requirement ${requirement.id}
> Auto-generated by the loopback milestone planner

## Planning Context

The milestones below are shaped to preserve a deterministic execution flow:
capture the baseline, turn it into executable slices, and leave a clean handoff
for readiness routing and session launch.

${sections.join('\n\n')}
`;
}

function prerequisiteDocument(requirement, milestones) {
  const sections = milestones.map((milestone) => {
    const existing = Array.isArray(milestone.data.prerequisites)
      ? milestone.data.prerequisites
      : [];
    const readyLines =
      existing.length > 0
        ? existing.map((item) => `- [${item.check_type}] ${item.description}`)
        : ['- [reference] Approved upstream planning materials are available'];
    return `## Milestone ${milestone.id}: ${milestone.data.name}

Current milestone prerequisites:
${existing.length > 0 ? existing.map((item) => `- [${item.check_type}] ${item.description}`).join('\n') : '- none listed'}

### Ready Now

${readyLines.join('\n')}

### Blocked / Missing
`;
  });

  return `# ${requirement.data.name} Prerequisite Analysis

> Requirement ${requirement.id}
> Auto-generated by the loopback prerequisite preparer

## Goal

Split milestone prerequisites into what is already satisfiable versus what still
needs intervention. The happy-path loopback runtime keeps the current milestone
set unblocked so the adaptive dispatcher can continue into task planning.

${sections.join('\n\n')}
`;
}

function workflowPlanDocument(requirement, tasks) {
  const sections = tasks.map((task) => `## Task ${task.id}: ${task.data.name}
Workflow Action: ${task.data.workflow_template_id ? 'reuse' : 'create'}
${task.data.workflow_template_id ? `Workflow ID: ${task.data.workflow_template_id}` : `Workflow Name: ${task.data.name} Auto Flow`}

### Workflow Description

Use a short, deterministic execution flow that reads the task document, applies
the scoped file contract, and emits a verifiable commit that can be judged.

### Steps

- s1 | inspect | Review the task contract and scoped files | inputs: task-document | outputs: scoped-plan
- s2 | execute | Modify only the scoped files for the task | inputs: scoped-plan | outputs: candidate-output
- s3 | verify | Summarize the result for judgement | inputs: candidate-output | outputs: verification-report`);

  return `# ${requirement.data.name} Workflow Preparation

> Requirement ${requirement.id}
> Auto-generated by the loopback workflow architect

## Goal

Assign exactly one workflow to each waiting task so the session launcher can
start execution without another manual planning pass.

${sections.join('\n\n')}
`;
}

function markerLine(taskId, timestamp) {
  return `RING-AUTO ${taskId} ${timestamp}`;
}

function commentWrappedMarker(extension, marker) {
  const ext = extension.toLowerCase();
  if (['.md', '.txt', '.text', '.log'].includes(ext) || ext === '') {
    return `\n## ${marker}\n\n- Generated by the loopback worker.\n`;
  }
  if (['.js', '.jsx', '.ts', '.tsx', '.java', '.c', '.cc', '.cpp', '.cs', '.go', '.rs', '.kt', '.swift', '.css', '.scss', '.less', '.sql'].includes(ext)) {
    return `\n// ${marker}\n`;
  }
  if (['.py', '.sh', '.rb', '.pl', '.yaml', '.yml', '.toml', '.ini', '.conf', '.properties', '.dockerfile'].includes(ext)) {
    return `\n# ${marker}\n`;
  }
  if (['.html', '.xml', '.svg'].includes(ext)) {
    return `\n<!-- ${marker} -->\n`;
  }
  return `\n${marker}\n`;
}

function updatedJsonContents(currentContents, taskId, timestamp) {
  let parsed;
  try {
    parsed = currentContents.trim() ? JSON.parse(currentContents) : {};
  } catch {
    parsed = {};
  }

  if (Array.isArray(parsed)) {
    return JSON.stringify([...parsed, { ring_auto: { task_id: taskId, timestamp } }], null, 2) + '\n';
  }
  if (parsed && typeof parsed === 'object') {
    return JSON.stringify({
      ...parsed,
      __ring_auto__: {
        ...(parsed.__ring_auto__ ?? {}),
        [taskId]: {
          updated_at: timestamp,
        },
      },
    }, null, 2) + '\n';
  }
  return JSON.stringify({ value: parsed, __ring_auto__: { [taskId]: { updated_at: timestamp } } }, null, 2) + '\n';
}

function nextFileContents(relativePath, currentContents, task, timestamp) {
  const extension = extname(relativePath).toLowerCase();
  if (extension === '.json') {
    return updatedJsonContents(currentContents, task.id, timestamp);
  }

  const marker = markerLine(task.id, timestamp);
  if (!currentContents) {
    if (extension === '.md') {
      return `# ${task.data.name}\n\n${commentWrappedMarker(extension, marker)}`;
    }
    return commentWrappedMarker(extension, marker).trimStart();
  }
  return `${currentContents.replace(/\s*$/, '')}${commentWrappedMarker(extension, marker)}`;
}

async function applyTaskFileChanges(repoRoot, task) {
  const repoCwd = resolveTaskRepoRoot(repoRoot, task);
  const filePaths = normalizePathList(task.data.scope?.file_paths);
  const timestamp = nowIso();

  for (const relativePath of filePaths) {
    const absolutePath = resolve(repoCwd, relativePath);
    const currentContents = await readFile(absolutePath, 'utf-8').catch(() => '');
    await mkdir(dirname(absolutePath), { recursive: true });
    await writeFile(
      absolutePath,
      nextFileContents(relativePath, currentContents, task, timestamp),
      'utf-8',
    );
  }

  return {
    repoCwd,
    filePaths,
    timestamp,
  };
}

function signedHeaders(workflowRun, payload, workerId) {
  const timestamp = nowIso();
  const secret = workflowRun.data.callback?.signing_secret;
  const signature = createHmac('sha256', secret)
    .update(`${timestamp}.${JSON.stringify(payload)}`)
    .digest('hex');
  return {
    headers: {
      authorization: `Bearer ${workflowRun.data.callback.token}`,
      'x-ring-timestamp': timestamp,
      'x-ring-signature': `sha256=${signature}`,
      'x-ring-key-version': String(workflowRun.data.callback.key_version ?? 1),
      'x-ring-worker-id': workerId,
    },
  };
}

function supportsProtocol(worker, protocol) {
  return Array.isArray(worker?.callback_protocols) && worker.callback_protocols.includes(protocol);
}

async function replanDepth(ring, task) {
  let depth = 0;
  let current = task;
  while (current?.data?.replanning?.parent_task_id) {
    depth += 1;
    current = await ring.read('task', current.data.replanning.parent_task_id).catch(() => null);
    if (!current) {
      break;
    }
  }
  return depth;
}

export function createLoopbackRuntime(
  repoRoot,
  ring,
  {
    orchestrator,
    sessionRunner,
    taskExecution,
  },
) {
  async function writeDocument(relativePath, contents) {
    const absolutePath = join(repoRoot, relativePath);
    await mkdir(dirname(absolutePath), { recursive: true });
    await writeFile(absolutePath, contents, 'utf-8');
  }

  async function completeRequirementJobs(config) {
    const jobs = await orchestrator.listJobs();
    let changed = false;

    for (const job of jobs) {
      if (!['requirement_dispatched', 'requirement_document_in_progress'].includes(job.status)) {
        continue;
      }
      const requirement = await ring.read('requirement', job.requirement_id);
      await writeDocument(
        job.requirement_document.document.path,
        requirementDocument(requirement, job),
      );
      await orchestrator.reportAgent(job.id, {
        agent_id: config.writer_agent_id,
        status: 'completed',
        note: 'Loopback writer completed the requirement document.',
      });
      changed = true;
    }

    return changed;
  }

  async function completeMilestoneJobs(config) {
    const jobs = await orchestrator.listJobs();
    let changed = false;

    for (const job of jobs) {
      if (!['milestone_dispatched', 'milestone_document_in_progress'].includes(job.status)) {
        continue;
      }
      const requirement = await ring.read('requirement', job.requirement_id);
      await writeDocument(
        job.milestone_plan.document.path,
        milestonePlanDocument(requirement),
      );
      await orchestrator.reportAgent(job.id, {
        agent_id: config.milestone_planner_agent_id,
        status: 'completed',
        note: 'Loopback milestone planner completed the milestone plan.',
      });
      changed = true;
    }

    return changed;
  }

  async function completePrerequisiteJobs(config) {
    const jobs = await orchestrator.listJobs();
    let changed = false;

    for (const job of jobs) {
      if (!['post_milestone_dispatched', 'post_milestone_in_progress'].includes(job.status)) {
        continue;
      }
      const requirement = await ring.read('requirement', job.requirement_id);
      const milestones = await Promise.all(
        (job.milestone_plan.generated_milestone_ids ?? []).map((id) => ring.read('milestone', id)),
      );
      await writeDocument(
        job.post_milestone.prerequisite_analysis.document.path,
        prerequisiteDocument(requirement, milestones),
      );
      await orchestrator.reportAgent(job.id, {
        agent_id: config.prerequisite_preparer_agent_id,
        status: 'completed',
        note: 'Loopback prerequisite preparer completed the readiness analysis.',
      });
      changed = true;
    }

    return changed;
  }

  async function completeWorkflowJobs(config) {
    const jobs = await orchestrator.listJobs();
    let changed = false;

    for (const job of jobs) {
      if (!['workflow_dispatched', 'workflow_in_progress'].includes(job.status)) {
        continue;
      }
      if (!job.workflow_preparation?.document?.path) {
        continue;
      }
      const waitingTasks = Array.isArray(job.workflow_preparation.waiting_tasks)
        ? job.workflow_preparation.waiting_tasks
        : [];
      if (waitingTasks.length === 0) {
        continue;
      }
      const requirement = await ring.read('requirement', job.requirement_id);
      const tasks = await Promise.all(
        waitingTasks.map((item) => ring.read('task', item.task_id)),
      );
      await writeDocument(
        job.workflow_preparation.document.path,
        workflowPlanDocument(requirement, tasks),
      );
      await orchestrator.reportAgent(job.id, {
        agent_id: config.workflow_designer_agent_id,
        status: 'completed',
        note: 'Loopback workflow architect completed the workflow plan.',
      });
      changed = true;
    }

    return changed;
  }

  async function performLoopbackAgentWork(config) {
    let changed = false;
    changed = (await completeRequirementJobs(config)) || changed;
    changed = (await completeMilestoneJobs(config)) || changed;
    changed = (await completePrerequisiteJobs(config)) || changed;
    changed = (await completeWorkflowJobs(config)) || changed;
    return changed;
  }

  async function chooseWorker(config, workflowRun) {
    const workers = await orchestrator.getWorkers();
    const allowedWorkerIds = normalizePathList(
      workflowRun.data.callback?.allowed_worker_ids ?? [config.worker_id],
    );
    const preferred = workers.find(
      (worker) =>
        worker.id === config.worker_id &&
        allowedWorkerIds.includes(worker.id) &&
        supportsProtocol(worker, config.default_callback_protocol),
    );
    if (preferred) {
      return {
        worker: preferred,
        protocol: config.default_callback_protocol,
      };
    }

    const worker =
      workers.find(
        (item) =>
          allowedWorkerIds.includes(item.id) &&
          supportsProtocol(item, RING_REPORT_PROTOCOL),
      ) ??
      workers.find(
        (item) =>
          allowedWorkerIds.includes(item.id) &&
          supportsProtocol(item, A2A_REPORT_PROTOCOL),
      ) ??
      null;

    if (!worker) {
      return null;
    }

    return {
      worker,
      protocol: supportsProtocol(worker, RING_REPORT_PROTOCOL)
        ? RING_REPORT_PROTOCOL
        : A2A_REPORT_PROTOCOL,
    };
  }

  async function reportLoopbackWorkflowRun(workflowRun, config) {
    const task = await ring.read('task', workflowRun.data.task_id);
    const workerSelection = await chooseWorker(config, workflowRun);
    if (!workerSelection) {
      return false;
    }

    const { repoCwd, filePaths, timestamp } = await applyTaskFileChanges(repoRoot, task);
    if (filePaths.length === 0) {
      return false;
    }

    await ensureGitIdentity(repoCwd);
    await runGit(repoCwd, ['add', '--force', '--', ...filePaths]);
    await runGit(repoCwd, [
      'commit',
      '--no-gpg-sign',
      '-m',
      `${config.commit_message_prefix}: ${task.id}`,
      '--',
      ...filePaths,
    ]);
    const commitSha = await runGit(repoCwd, ['rev-parse', 'HEAD']);

    const currentStep = workflowRun.data.steps?.[workflowRun.data.current_step_index ?? 0] ?? null;
    const payload =
      workerSelection.protocol === A2A_REPORT_PROTOCOL
        ? {
            protocol: A2A_REPORT_PROTOCOL,
            worker: {
              id: workerSelection.worker.id,
              display_name: workerSelection.worker.display_name ?? workerSelection.worker.id,
            },
            task: {
              id: workflowRun.id,
              kind: 'workflow-run',
              status: {
                state: 'completed',
                message: 'Loopback worker completed execution.',
              },
              artifacts: [
                {
                  kind: 'git_commit',
                  uri: `git+commit://${commitSha}`,
                },
              ],
              metadata: {
                step_id: currentStep?.step_id ?? null,
                judge_agent_id: config.judge_agent_id,
                outputs: {
                  timestamp,
                },
              },
            },
          }
        : {
            status: 'completed',
            actor: workerSelection.worker.display_name ?? workerSelection.worker.id,
            worker_id: workerSelection.worker.id,
            step_id: currentStep?.step_id ?? null,
            note: 'Loopback worker completed execution.',
            commit_sha: commitSha,
            judge_agent_id: config.judge_agent_id,
            outputs: {
              timestamp,
            },
          };

    await sessionRunner.reportWorkflowRun(
      workflowRun.id,
      payload,
      signedHeaders(workflowRun, payload, workerSelection.worker.id),
    );
    return true;
  }

  async function performLoopbackWorkerWork(config) {
    const workflowRuns = await ring.list('workflow-run');
    let changed = false;

    for (const workflowRun of workflowRuns) {
      if (workflowRun.status !== 'running') {
        continue;
      }
      const callbackStatus = workflowRun.data.callback?.status ?? 'pending';
      if (!['active', 'retry_scheduled'].includes(callbackStatus)) {
        continue;
      }
      const nextRetryAt = workflowRun.data.callback?.next_retry_at;
      if (callbackStatus === 'retry_scheduled' && nextRetryAt && Date.parse(nextRetryAt) > Date.now()) {
        continue;
      }
      changed = (await reportLoopbackWorkflowRun(workflowRun, config)) || changed;
    }

    return changed;
  }

  async function performAutoJudge(config) {
    const tasks = await ring.list('task');
    let changed = false;

    for (const task of tasks) {
      if (
        task.status === 'in_progress' &&
        task.data.execution?.review_status === 'awaiting_judgement'
      ) {
        await taskExecution.judge(task.id, {
          verdict: 'approved',
          judge_agent_id: config.judge_agent_id,
          note: 'Loopback judge approved the task output.',
        });
        changed = true;
      }
    }

    return changed;
  }

  async function launchStandaloneTask(task) {
    if (
      task.status !== 'ready' ||
      task.session_id != null ||
      !trimString(task.data.workflow_template_id) ||
      !trimString(task.data.replanning?.parent_task_id)
    ) {
      return false;
    }

    const requirement = await ring.read('requirement', task.data.requirement_id);
    const workflow = await ring.read('workflow', task.data.workflow_template_id);
    const orchestratorConfig = await orchestrator.getConfig();
    const runnerConfig = orchestratorConfig.session_runner ?? {};
    const sessionId = await ring.newId('session', {
      name: `${task.data.name} auto redispatch`,
    });
    const runId = await ring.newId('workflow-run', {
      name: `${task.id} ${workflow.data.name}`,
    });

    const createSessionResult = await ring.create('session', {
      id: sessionId,
      status: 'preparing',
      created_by: 'loopback-runtime',
      session_id: sessionId,
      data: {
        requirement_id: requirement.id,
        milestone_id: task.data.milestone_id,
        milestone_ids: [task.data.milestone_id],
        task_ids: [task.id],
        workflow_run_ids: [runId],
        evaluation_id: null,
        distillation_id: null,
        context_injected: {
          workflow_template: workflow.id,
          distillations_applied: [],
          registry_rank_at_selection: null,
        },
        execution_log: [
          {
            timestamp: nowIso(),
            event: 'loopback_replan_launch',
            actor: 'loopback-runtime',
            detail: `Auto-launched redispatched task ${task.id}.`,
          },
        ],
      },
    });
    if (!createSessionResult.ok) {
      throw new Error(`Loopback session creation failed: ${JSON.stringify(createSessionResult.errors)}`);
    }

    const createRunResult = await ring.create('workflow-run', {
      id: runId,
      status: 'pending',
      created_by: 'loopback-runtime',
      session_id: sessionId,
      data: {
        workflow_template_id: workflow.id,
        workflow_template_version: workflow.version,
        task_id: task.id,
        current_step_index: 0,
        callback: {
          auth_scheme: 'bearer',
          report_url: null,
          token: null,
          signing_secret: null,
          signature_algorithm: 'hmac-sha256',
          key_version: 1,
          status: 'pending',
          issued_at: null,
          prepared_at: null,
          last_report_at: null,
          last_retry_at: null,
          last_rotated_at: null,
          next_retry_at: null,
          report_timeout_ms: runnerConfig.report_timeout_ms ?? 120000,
          max_retries: 0,
          retry_count: 0,
          retry_backoff_ms: runnerConfig.retry_backoff_ms ?? 30000,
          signature_ttl_ms: runnerConfig.signature_ttl_ms ?? 300000,
          timeout_at: null,
          packet_path: null,
          allowed_worker_ids: [],
          accepted_protocols: [RING_REPORT_PROTOCOL],
          last_worker_id: null,
          last_protocol: null,
          last_error: null,
        },
        reports: [],
        steps: workflow.data.steps.map((step) => ({
          step_id: step.id,
          status: 'pending',
          started_at: null,
          ended_at: null,
          outputs: {},
          notes: null,
        })),
      },
    });
    if (!createRunResult.ok) {
      throw new Error(`Loopback workflow-run creation failed: ${JSON.stringify(createRunResult.errors)}`);
    }

    const taskUpdate = await ring.update('task', task.id, {
      session_id: sessionId,
      status: 'in_progress',
      data: {
        workflow_template_id: workflow.id,
        workflow_run_id: runId,
      },
    });
    if (!taskUpdate.ok) {
      throw new Error(`Loopback task relaunch failed: ${JSON.stringify(taskUpdate.errors)}`);
    }

    return true;
  }

  async function performAutoReplan(config) {
    const tasks = await ring.list('task');
    let changed = false;

    for (const task of tasks) {
      if (
        task.status !== 'failed' ||
        task.data.replanning?.status !== 'awaiting_replan'
      ) {
        continue;
      }

      const depth = await replanDepth(ring, task);
      const reason = trimString(task.data.replanning?.source_failure) ?? 'unknown_failure';
      const canRedispatch =
        depth < config.max_replan_depth &&
        ['workflow_failed', 'workflow_timeout', 'review_rejected'].includes(reason) &&
        trimString(task.data.workflow_template_id);

      const replannedTask = await taskExecution.replan(task.id, canRedispatch
        ? {
            verdict: 'redispatch',
            replanner_agent_id: config.replanner_agent_id,
            note: `Loopback replanner redispatched the task after ${reason}.`,
            task: {
              workflow_template_id: task.data.workflow_template_id,
            },
          }
        : {
            verdict: 'terminal',
            replanner_agent_id: config.replanner_agent_id,
            note: `Loopback replanner marked the task terminal after ${reason}.`,
          });

      if (canRedispatch && replannedTask.data.replanning?.successor_task_id) {
        const successorTask = await ring.read('task', replannedTask.data.replanning.successor_task_id);
        await launchStandaloneTask(successorTask);
      }
      changed = true;
    }

    return changed;
  }

  async function tick() {
    const orchestratorConfig = await orchestrator.getConfig();
    const config = mergeAutomationConfig(orchestratorConfig);
    if (!config.enabled) {
      return {
        ok: true,
        skipped: true,
        changed: false,
      };
    }

    let changed = false;
    if (config.loopback_agents) {
      changed = (await performLoopbackAgentWork(orchestratorConfig)) || changed;
    }
    if (config.loopback_worker) {
      changed = (await performLoopbackWorkerWork(config)) || changed;
    }
    if (config.auto_judge) {
      changed = (await performAutoJudge(config)) || changed;
    }
    if (config.auto_replan) {
      changed = (await performAutoReplan(config)) || changed;
    }

    if (changed) {
      await sessionRunner.tick();
      await sessionRunner.tick();
    }

    return {
      ok: true,
      skipped: false,
      changed,
    };
  }

  return {
    tick,
  };
}
